micronaut:
    application:
        name: acme-pay
        instance:
            id: ${random.shortuuid}
    server:
        port: -1
        context-path: acme-pay
    caches:
        discovery-client:
            enabled: false
            #expire-after-access: 60s

endpoints:
  info:
    enabled: true
    sensitive: false

consul:
    client:
        registration:
            enabled: true
            deregister: true
            defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
            check:
                deregister-critical-service-after: 30s 
        prefer-ip-address: true        

# Message Queue
rabbitmq:
    uri: amqp://localhost:5672
    username: mq-acme
    password: mq-acme

# management and tracing
tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1 
