micronaut:
    application:
        name: acme-travel
        instance:
            id: ${random.shortuuid}
    server:
        port: -1
        context-path: acme-travel
    caches:
        discovery-client:
            enabled: false
            #expire-after-access: 60s
    io: #restart app when source change
        watch:
            paths: src/main
            restart: true

endpoints:
  info:
    enabled: true
    sensitive: false

# service discovery
consul:
    client:
        registration:
            enabled: true
            deregister: true
            defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
            check:
                deregister-critical-service-after: 30s 
        prefer-ip-address: true        

# Message Queue
rabbitmq:
    uri: amqp://localhost:5672
    username: guest
    password: guest
    
# management and tracing
tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1 
      
#micronaut:
#  router:
#    static-resources:
#      swagger:
#        paths: classpath:META-INF/swagger
#        mapping: /swagger/**